#
# Reference
# https://bukkit.gamepedia.com/Plugin_YAML
#
name: SecretSanta
main: net.peacefulcraft.secretsanta.SecretSanta
version: 0.0.1
api-version: 1.16
website: https://www.peacefulcraft.net/
depend: []
softdepend: []

commands:
  secretsanta:
    aliases: [ 'ss' ]
    description: Main command for Secret Santa
    usage: /<command> [ help | register | submit | getgift ]

permissions:
  templateus.*:
    description: Gives access to all templateus commands
    children:
      templateus.example: true
  templateus.example:
    description: Gives access to tempateus' example command
    default: op
